### ISSUE TITLE
Undefined software license

### ISSUE THREAD

**Issue by maxwell-gumley-fgt** [tttapa/tttapa.github.io#2]
I really like the code you wrote here for the moving average:
[https://tttapa.github.io/Pages/Mathematics/Systems-and-Control-Theory/Digital-filters/Simple%20Moving%20Average/Simple-Moving-Average.html#plotting-the-frequency-response-impulse-response-and-step-response-in-python](https://tttapa.github.io/Pages/Mathematics/Systems-and-Control-Theory/Digital-filters/Simple%20Moving%20Average/Simple-Moving-Average.html#plotting-the-frequency-response-impulse-response-and-step-response-in-python)

However, I'm not allowed to use it unless you post a license permitting me to do so.  I recommend using the MIT license because it protects you as the original author but also allowed others to use your code without limitation.

See this github page for an explaination:
[https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/licensing-a-repository](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/licensing-a-repository)

Cheers,
Maxwell Gumley

**Comment by tttapa** [comment]
Hi, thanks for letting me know!

I usually license my code under the GPLv3, since this GitHub pages repository includes a significant amount of code of my other repositories, the GPLv3 is the most logical choice for this repository as well.

This shouldn't make too much of a difference unless you plan on re-distributing it as part of a closed-source project.

Pieter

**Comment by maxwell-gumley-fgt** [comment]
The app I'm building is intended for internal company use at the moment, but so far I've managed to avoid any restrictive licenses.  I don't know if we will take parts of this to make a product some day.  

I think I found a way to compute this without iterating, by using a Taylor series approximation.  It doesn't need to be very precise because we have to round to the nearest integer kernel size anyway. Have you seen this? https://dsp.stackexchange.com/a/28186

**Comment by tttapa** [comment]
I might change my mind when I work in a company/commercial setting later, but I (naively?) believe in open-source software. 
You have to understand that I write these pages purely for educational purposes, and for-profit companies copying the code without giving anything back to the community doesn't really fit into that.

That being said, feel free to use the Python script you linked to earlier if it helps you. The code will probably be very similar to the examples that come with the SciPy documentation anyway.  

Thanks for that link, a very interesting derivation!  
For a real application that might have to compute the cutoff frequency multiple times, the approximation is probably the way to go. The Newton iterations are not that expensive though, since the analytical derivative is easy to find, so it works fine for a simple script like that.

**Comment by maxwell-gumley-fgt** [comment]
I love open source software too, and I write plenty of it.  The problem with your approach is that GPL makes it impossible for companies to use the code while making a profit and paying their employees.  With LGPL or MIT license, a company can use that code, and they may or may not contribute to that open source library, but at least there is a chance.  With LGPL, they can use the open source software, and must provide the community with all improvements they make.  GPL is actually harming open source efforts in my opinion.

**Comment by tttapa** [comment]
I understand that the GPL makes it harder for companies to use it in proprietary software, but that's sort of the point. Like I said, most of what I write is purely educational, and the other pages and repositories are hobby projects aimed at other hobbyists, so I have no interest in companies using it in proprietary projects, even if there's a small chance that they might contribute.

There are business models to make a profit from open-source code, such as offering support, selling related hardware or services, or offering a multi-license with the GPL for open-source users and commercial licenses for people who don't want to use it under GPL. It might not be an option for all companies, but I think saying that the GPL is making it impossible to pay their employees is a bit of an exageration.

I'll keep your advice in mind if I ever release a library intended for wide use, but for now, the GPL works fine for me.

**Comment by maxwell-gumley-fgt** [comment]
Even if we disagree about GPL vs LGPL, I still appreciate all the work that you make public for the sake of education of others.  Thanks for what you do.
Cheers,
Max
